version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    tty: true  
    stdin_open: true
    healthcheck:
      test: curl --fail http://localhost:3333/health || exit 1
      interval: 20s
      retries: 1
      start_period: 10s
      timeout: 5s  
    networks:
      - my-network
    volumes:
     - ./server:/app

  client:
    environment:
      NETWORK: 'docker'
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      server:
        condition: service_healthy 
    deploy:
      replicas: 5     
    volumes:
      - ./client:/app
    networks:
      - my-network  
    stdin_open: true 
    tty: true   
 

networks:
  my-network:

